I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1869, in script call
    call .practice_haha
  File "game/script.rpy", line 888, in script
    if energy >= 3:
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1869, in script call
    call .practice_haha
  File "game/script.rpy", line 888, in script
    if energy >= 3:
  File "C:\Game Dev Stuff\renpy-8.2.1-sdk\renpy\execution.py", line 61, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
Miracle Cafe 1.0
Wed Oct  2 23:13:34 2024
