I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 964, in script call
    call opening_hours
  File "game/script.rpy", line 3081, in script call
    call week_events
  File "game/script.rpy", line 2344, in script call
    call stat_events
  File "game/script.rpy", line 1868, in script call
    call tam_help
  File "game/script.rpy", line 1948, in script call
    call .practice_haha
  File "game/script.rpy", line 960, in script call
    call day
  File "game/script.rpy", line 3054, in script call
    call screen opening_options
  File "game/script.rpy", line 2669, in script call
    call LI_sched
  File "game/script.rpy", line 2634, in script call
    call tam_gym
  File "game/script.rpy", line 2896, in script call
    call .bros
  File "game/script.rpy", line 964, in script call
    call opening_hours
  File "game/script.rpy", line 3081, in script call
    call week_events
  File "game/script.rpy", line 2344, in script call
    call stat_events
  File "game/script.rpy", line 1893, in script call
    call rand_events.makeover_makeover
  File "game/script.rpy", line 2545, in script call
    call .accept
  File "game/script.rpy", line 960, in script call
    call day
  File "game/script.rpy", line 3054, in script call
    call screen opening_options
  File "game/script.rpy", line 2669, in script call
    call LI_sched
  File "game/script.rpy", line 2637, in script call
    call tam_park
  File "game/script.rpy", line 943, in script call
    call sunday_break
  File "game/script.rpy", line 3016, in script
    $ current_profit += (49 + reputation) /2
  File "game/script.rpy", line 3016, in <module>
    $ current_profit += (49 + reputation) /2
NameError: name 'reputation' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 964, in script call
    call opening_hours
  File "game/script.rpy", line 3081, in script call
    call week_events
  File "game/script.rpy", line 2344, in script call
    call stat_events
  File "game/script.rpy", line 1868, in script call
    call tam_help
  File "game/script.rpy", line 1948, in script call
    call .practice_haha
  File "game/script.rpy", line 960, in script call
    call day
  File "game/script.rpy", line 3054, in script call
    call screen opening_options
  File "game/script.rpy", line 2669, in script call
    call LI_sched
  File "game/script.rpy", line 2634, in script call
    call tam_gym
  File "game/script.rpy", line 2896, in script call
    call .bros
  File "game/script.rpy", line 964, in script call
    call opening_hours
  File "game/script.rpy", line 3081, in script call
    call week_events
  File "game/script.rpy", line 2344, in script call
    call stat_events
  File "game/script.rpy", line 1893, in script call
    call rand_events.makeover_makeover
  File "game/script.rpy", line 2545, in script call
    call .accept
  File "game/script.rpy", line 960, in script call
    call day
  File "game/script.rpy", line 3054, in script call
    call screen opening_options
  File "game/script.rpy", line 2669, in script call
    call LI_sched
  File "game/script.rpy", line 2637, in script call
    call tam_park
  File "game/script.rpy", line 943, in script call
    call sunday_break
  File "game/script.rpy", line 3016, in script
    $ current_profit += (49 + reputation) /2
  File "C:\renpy-8.3.2-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\renpy-8.3.2-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 3016, in <module>
    $ current_profit += (49 + reputation) /2
NameError: name 'reputation' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.2.24090902
Miracle Cafe 1.0
Thu Oct 10 18:06:27 2024
